Logging
ArchBacon/Lumina-Engine pull request #13
Opened 2024-04-26 19:17 UTC by ArchBacon

example trace log: `[21:15:55] ENGINE: Engine::Run 0.000107s`

2024-04-26 19:28 UTC, ArchBacon commented on engine/source/public/core/log.hpp
> +        }
Ik wil dit eigenlijk op een single line hebben, maar clang staat dat niet toe :(
```c++
template <typename... Args>
static void Error(Args... args) { logger->error(std::forward<Args>(args)...); }
```

2024-04-26 20:48 UTC, VengarvdWal requested changes
Could you write some comments, what logger functions do, and when they should be used?

2024-04-27 09:10 UTC, ArchBacon commented
> Could you write some comments, what logger functions do, and when they should be used?

I have added a comment with a small explanation to the class

2024-04-27 10:03 UTC, VengarvdWal submitted a review, later dismissed

2024-04-27 20:33 UTC, merged